#!/bin/bash

# Sets up vault to generate and sign certs directly by a root certificate (no intermediates involved).

vault secrets enable pki

# 1 year TTLs by default
vault secrets tune -max-lease-ttl=87600h pki

# generate root certificate
vault write -format=json pki/root/generate/internal common_name=pki.getweave.com ttl=87600h

# setup CRL/OCSP URLs (must be accessible to all clients)
vault write -format=json pki/config/urls issuing_certificates="http://vault.getweave.com:8200/v1/pki/ca" crl_distribution_points="http://vault.getweave.com:8200/v1/pki/crl"

# configure role to use
vault write pki/roles/example-dot-com \
    allowed_domains=example.com \
    allow_subdomains=true max_ttl=72h
