#!/bin/bash -xe

# Imports existing intermediate for use

# Sets up vault to generate and sign certs using a root AND intermediate.
vault secrets enable pki
vault secrets tune -max-lease-ttl=87600h pki

# generate root certificate
vault write -format=json pki/root/generate/exported common_name=pki-root.example.net ttl=43800h > root-cert.json

# intermediate secret engine
vault secrets enable -path=pki_int pki
vault secrets tune -max-lease-ttl=43800h pki_int

## generate intermediate CSR
vault write -format=json  pki_int/intermediate/generate/exported common_name="Some Intermediate Authority" ttl=43800h > pki_csr.json

jq -r ".data.private_key" pki_csr.json > pki_int.key
jq -r ".data.csr" pki_csr.json > pki_int.csr

## sign intermediate CSR with root cert
vault write -field=certificate pki/root/sign-intermediate csr=@pki_int.csr format=pem_bundle ttl=43800h > signed_certificate.pem

# set intermediate CA to root-signed cert
vault write -format=json pki_int/intermediate/set-signed certificate=@signed_certificate.pem

# setup CRL/OCSP URLs (must be accessible to all clients)
vault write -format=json pki_int/config/urls issuing_certificates="http://localhost:8200/v1/pki_int/ca" crl_distribution_points="http://localhost:8200/v1/pki_int/crl"
# setup role
vault write -format=json pki_int/roles/example-dot-net \
    allowed_domains=example.net \
    allow_subdomains=true max_ttl=72h

# set up new engine that will not use root certificate
vault secrets enable -path=pki_other pki
vault secrets tune -max-lease-ttl=43800h pki_other

# TODO create pem bundle with CA key and cert from above
cat pki_int.key > ca_bundle.pem
cat signed_certificate.pem >> ca_bundle.pem

# TODO add root to CA chain. we may not need this depending on ClientAuth mode

# set the CA for this pki engine
vault write -format=json pki_other/config/ca \
    pem_bundle=@ca_bundle.pem \

# setup role
# one role per app until we have better authorization
vault write -format=json pki_other/roles/example-dot-net \
    allowed_domains=example.net \
    allow_subdomains=true max_ttl=72h

# issue cert. Root CA is not returned, since this is typically trusted by the underlying OS
vault write -format=json pki_other/issue/example-dot-net \
       common_name=foo.example.net > client.json


jq -r ".data.certificate" client.json > client-cert.pem
jq -r ".data.private_key" client.json > client-key.pem
